@startumlFoo
actor       "Contribuyente\nEmisor" as Contribuyente
participant SII

Contribuyente -> SII : Solicita 1000 folios para Facturas Electrónicas
SII -> Contribuyente : Un CAF desde el rango 501 al 1500
@enduml

