@startumlFoo
actor       "Contribuyente\nEmisor" as Contribuyente
participant SII

Contribuyente -> SII : Solicita folios
activate SII
SII -> Contribuyente : Entrega archivo "Código de Autorización de Folios (CAF)"
deactivate SII
@enduml

